### ISSUE TITLE
分页大小、列表项点击事件、分割线

### ISSUE THREAD

**Issue by FindaBottle** [gengqiquan/RefreshLayout#1]
首先感谢作者的分享。在使用中遇到一些需要完善地方。首先分页大小设置无效，在判断hasMore的时候是写死的20，其次没有列表项点击事件；然后没有分割线，scrollbar也无法设置。希望能完善

**Comment by gengqiquan** [comment]
@FindaBottle  sorry.代码其实修改了，但是更新不上jcenter了。出现某明奇妙的问题。我的账号一直不可用。搞了很多天了，在努力发布上去。。。。。

**Comment by gengqiquan** [comment]
@FindaBottle 重新注册了个账号，已经提交了。。应该很快就通过审核可用了
